import { JSDOM } from "jsdom";
const dom = new JSDOM("<!doctype html><html><body><div id='root'></div></body></html>", { url: "http://localhost:3000/analysis", pretendToBeVisual: true });
globalThis.window = dom.window; globalThis.document = dom.window.document; globalThis.navigator = dom.window.navigator;
globalThis.HTMLElement = dom.window.HTMLElement;
globalThis.requestAnimationFrame = (cb) => setTimeout(cb, 16); globalThis.cancelAnimationFrame = (id) => clearTimeout(id);
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
globalThis.fetch = () => Promise.resolve({ ok: false, status: 502, json: () => Promise.resolve({}) });
const React = (await import("react")).default;
const { createRoot } = await import("react-dom/client");
const { act } = await import("react");
const MacroApp = (await import("./.smoke20-bundle.mjs")).default;
const root = createRoot(document.getElementById("root"));
await act(async () => { root.render(React.createElement(MacroApp)); });
await act(async () => { await new Promise((r) => setTimeout(r, 1500)); });
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
console.log("TITLE:", JSON.stringify($(".ct-title")?.textContent));
$$(".ct-readout .ct-cell").forEach((c, i) => console.log("CELL", i, JSON.stringify(c.textContent)));
const metas = $$(".ct-block-head .ct-block-meta").map((m) => m.textContent);
console.log("METAS:", JSON.stringify(metas));
console.log("ACC samples via DOM:", $$(".ct-acc-row").length, "rows");
process.exit(0);
