// lib/series.js
// Definisi indikator makroekonomi & pemetaan ke seri FRED.
// Kategori: "inflasi" | "tenaga-kerja" | "moneter" | "pertumbuhan" | "pasar" | "konsumen"
// frek: "M" bulanan | "Q" kuartalan | "D" harian

const SERIES_RAW = [
  {
    id: "nfp",
    typicalDay: 5, // rilis Jumat pertama bulan berikutnya (jadwal resmi: data/schedule-us.json)
    ffDivisor: 1000, // ForexFactory menulis "58K" → 58 ribu
    name: "Nonfarm Payrolls (NFP)",
    short: "NFP",
    category: "tenaga-kerja",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "PAYEMS",
    mode: "monthly_change",
    unit: "ribu",
    decimals: 1,
    impact: "High",
    release: "Awal bulan (hari irreguler, Rabu–Jumat), 08:30 ET (19:30/20:30 WIB)",
    about: "Perubahan jumlah tenaga kerja non-pertanian (paling banyak menentukan pergerakan pasar).",
    why: "Menunjukkan kesehatan pasar tenaga kerja & arah kebijakan suku bunga The Fed.",
    fx: "Data kuat → USD kuat (hawkish). Data lemah/lebih rendah dari estimasi → USD melemah.",
  },
  {
    id: "unemp",
    typicalDay: 5,
    name: "Unemployment Rate",
    short: "Unemployment",
    category: "tenaga-kerja",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "UNRATE",
    mode: "level",
    unit: "%",
    decimals: 1,
    impact: "High",
    release: "Bersamaan dengan NFP, 08:30 ET",
    about: "Persentase angkatan kerja yang menganggur.",
    why: "Tingkat pengangguran rendah memicu kekhawatiran inflasi upah.",
    fx: "Turun → USD bullish; naik mendadak → USD bearish.",
  },
  {
    id: "cpi",
    typicalDay: 12,
    name: "Consumer Price Index (CPI) y/y",
    short: "CPI",
    category: "inflasi",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    // indeks NSA = basis resmi BLS/ForexFactory untuk angka y/y (1 desimal)
    fred: "CPIAUCNS",
    mode: "yoy_pct",
    unit: "%",
    decimals: 1,
    impact: "High",
    release: "Sekitar pertengahan bulan, 08:30 ET",
    about: "Perubahan harga barang & jasa yang dibeli konsumen (YoY).",
    why: "Ukuran inflasi utama yang dipantau The Fed.",
    fx: "Naik di atas target → The Fed hawkish → USD kuat. Turun → USD lemah.",
  },
  {
    id: "corecpi",
    typicalDay: 12,
    name: "Core CPI y/y",
    short: "Core CPI",
    category: "inflasi",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "CPILFENS",
    mode: "yoy_pct",
    unit: "%",
    decimals: 1,
    impact: "High",
    release: "Bersamaan dengan CPI",
    about: "CPI tanpa makanan & energi (lebih stabil, jadi fokus pasar).",
    why: "The Fed lebih memperhatikan core CPI untuk kebijakan.",
    fx: "Core CPI tinggi → USD bullish; rendah → USD bearish.",
  },
  {
    id: "ppi",
    typicalDay: 13,
    name: "Producer Price Index (PPI) m/m",
    short: "PPI",
    category: "inflasi",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    // PPI Final Demand (basis headline BLS & ForexFactory "PPI m/m")
    fred: "PPIFIS",
    mode: "mom_pct",
    unit: "%",
    decimals: 1,
    impact: "High",
    release: "Sekitar pertengahan bulan, 08:30 ET",
    about: "Perubahan bulanan harga di tingkat produsen — PPI Final Demand (indikator pendahulu inflasi konsumen).",
    why: "Biaya produksi yang naik biasanya terbawa ke harga konsumen.",
    fx: "PPI tinggi → tekanan inflasi → USD bisa menguat.",
  },
  {
    id: "corepce",
    name: "Core PCE Price Index (m/m)",
    short: "Core PCE",
    category: "inflasi",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "PCEPILFE",
    mode: "mom_pct",
    unit: "%",
    decimals: 1,
    typicalDay: 28,
    impact: "High",
    release: "Akhir bulan, 08:30 ET (19:30 WIB)",
    about: "Indeks harga pengeluaran konsumsi pribadi inti (tanpa makanan & energi) — ukuran inflasi favorit The Fed.",
    why: "The Fed mengacu pada PCE inti untuk menilai tren inflasi jangka menengah.",
    fx: "Core PCE tinggi → tekanan kenaikan suku bunga → USD bisa menguat.",
  },
  {
    id: "ahe",
    typicalDay: 5,
    name: "Average Hourly Earnings m/m",
    short: "AHE",
    category: "tenaga-kerja",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "CES0500000003",
    mode: "mom_pct", // basis ForexFactory "Average Hourly Earnings m/m"
    unit: "%",
    decimals: 1,
    impact: "Medium",
    release: "Bersamaan dengan NFP",
    about: "Perubahan bulanan upah rata-rata per jam (m/m).",
    why: "Kenaikan upah mendorong inflasi upah dan ekspektasi suku bunga.",
    fx: "Upah naik → USD bullish.",
  },
  {
    id: "fedfunds",
    name: "Fed Funds Target Rate",
    short: "Fed Funds",
    category: "moneter",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "DFEDTARU",
    mode: "level_last", // nilai akhir bulan = target setelah FOMC bulan tsb
    obsRule: "same-month",
    unit: "%",
    decimals: 2,
    impact: "High",
    release: "Putusan FOMC 8x/tahun, 14:00 ET",
    about: "Batas atas target suku bunga The Fed.",
    why: "Level suku bunga menentukan biaya dana secara global.",
    fx: "Kenaikan/ekspektasi kenaikan → USD kuat; pemotongan → USD lemah.",
  },
  {
    id: "dgs10",
    name: "U.S. 10-Year Treasury Yield",
    short: "10Y Yield",
    category: "pasar",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "D",
    fred: "DGS10",
    mode: "level",
    unit: "%",
    decimals: 2,
    impact: "Medium",
    release: "Harian, pasar obligasi",
    about: "Imbal hasil obligasi pemerintah AS tenor 10 tahun.",
    why: "Imbal hasil adalah 'harga' uang; bergerak searah dengan USD.",
    fx: "Yield naik → aliran modal masuk → USD menguat.",
  },
  {
    id: "retail",
    typicalDay: 15,
    name: "Retail Sales m/m",
    short: "Retail Sales",
    category: "konsumen",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "RSAFS", // total ritel & jasa makanan (headline Census/ForexFactory)
    mode: "mom_pct",
    unit: "%",
    decimals: 1,
    impact: "Medium",
    release: "Sekitar pertengahan bulan",
    about: "Perubahan penjualan ritel bulanan.",
    why: "Proksi utama belanja konsumen (2/3 ekonomi AS).",
    fx: "Kuat → USD bullish; lemah → USD bearish.",
  },
  {
    id: "umich",
    typicalDay: 12,
    name: "Michigan Consumer Sentiment",
    short: "Michigan",
    category: "konsumen",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "UMCSENT",
    mode: "level",
    obsRule: "same-month", // prelim 11 Sep = sentimen SEPTEMBER (bukan bulan sebelumnya)
    unit: "index",
    decimals: 1,
    impact: "Low",
    release: "Dua kali per bulan (preliminary & final)",
    about: "Kepercayaan / sentimen konsumen terhadap ekonomi.",
    why: "Menangkap ekspektasi inflasi konsumen.",
    fx: "Sentimen naik → risiko positif → USD bisa menguat.",
  },
  {
    id: "indpro",
    name: "Industrial Production",
    short: "Ind. Production",
    category: "pertumbuhan",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "INDPRO",
    mode: "mom_pct",
    unit: "%",
    decimals: 1,
    typicalDay: 15,
    impact: "Low",
    release: "Sekitar pertengahan bulan",
    about: "Perubahan output pabrik, pertambangan, & utilitas.",
    why: "Indikator aktivitas ekonomi sektor produksi.",
    fx: "Produksi naik → sentimen ekonomi membaik.",
  },
  {
    id: "gdp",
    name: "Prelim GDP (q/q) Annualized",
    short: "GDP",
    category: "pertumbuhan",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "Q",
    // seri resmi BEA "Real GDP: Percent Change from Preceding Period" (q/q SAAR, 1 desimal)
    fred: "A191RL1Q225SBEA",
    mode: "raw",
    unit: "%",
    decimals: 1,
    typicalDay: 28,
    impact: "High",
    release: "3x per kuartal (advance/prelim/final), 08:30 ET (19:30 WIB)",
    about: "Pertumbuhan PDB riil per kuartal, annualized (q/q) — angka awal (preliminary) dari BEA yang biasanya masih direvisi.",
    why: "Angka pertumbuhan terlebar; menentukan narasi 'ekonomi kuat vs perlambatan' dan ruang kebijakan The Fed.",
    fx: "GDP kuat → USD bullish; lemah → ekspektasi cut → USD bearish.",
  },
  {
    id: "eu_cpi",
    name: "Euro Area HICP Inflation",
    short: "EZ CPI",
    category: "inflasi",
    country: "EZ",
    countryName: "Zona Euro",
    freq: "M",
    fred: "CP0000EZ19M086NEST",
    mode: "yoy_pct",
    unit: "%",
    decimals: 1,
    impact: "High",
    release: "Flash estimate tiap akhir bulan / laporan awal",
    about: "Harmonized Index of Consumer Prices untuk Zona Euro.",
    why: "Menentukan kebijakan ECB.",
    fx: "Inflasi EZ tinggi → EUR kuat (ECB hawkish).",
  },
  {
    id: "eu_unemp",
    name: "Euro Area Unemployment Rate",
    short: "EZ Unemployment",
    category: "tenaga-kerja",
    country: "EZ",
    countryName: "Zona Euro",
    freq: "M",
    fred: "LRHUTTTTEZM156S",
    mode: "level",
    unit: "%",
    decimals: 1,
    impact: "Low",
    release: "Akhir bulan (Eurostat)",
    about: "Tingkat pengangguran Zona Euro.",
    why: "Indikator pasar tenaga kerja Eropa.",
    fx: "Pengangguran turun → EUR sedikit bullish.",
  },
  {
    id: "uk_cpi",
    name: "U.K. CPI Inflation",
    short: "UK CPI",
    category: "inflasi",
    country: "UK",
    countryName: "Inggris",
    freq: "M",
    fred: "GBRCPIALLMINMEI",
    mode: "yoy_pct",
    unit: "%",
    decimals: 1,
    impact: "High",
    release: "Sekitar pertengahan bulan (ONS)",
    about: "Indeks harga konsumen Inggris.",
    why: "Menentukan kebijakan Bank of England.",
    fx: "Inflasi UK tinggi → GBP kuat (BoE hawkish).",
  },
  {
    id: "uk_unemp",
    name: "U.K. Unemployment Rate",
    short: "UK Unemployment",
    category: "tenaga-kerja",
    country: "UK",
    countryName: "Inggris",
    freq: "M",
    fred: "LRHUTTTTGBM156S",
    mode: "level",
    unit: "%",
    decimals: 1,
    impact: "Medium",
    release: "Bulanan (ONS)",
    about: "Tingkat pengangguran Inggris.",
    why: "Kesehatan pasar kerja memengaruhi kebijakan BoE.",
    fx: "Pengangguran turun → GBP bullish.",
  },
  {
    id: "jp_cpi",
    name: "Japan CPI Inflation",
    short: "JP CPI",
    category: "inflasi",
    country: "JP",
    countryName: "Jepang",
    freq: "M",
    fred: "JPNCPIALLMINMEI",
    mode: "yoy_pct",
    unit: "%",
    decimals: 1,
    impact: "Medium",
    release: "Sekitar akhir bulan",
    about: "Indeks harga konsumen Jepang.",
    why: "Inflasi menentukan kebijakan Bank of Japan (normalisasi suku bunga).",
    fx: "Inflasi JP tinggi → JPY cenderung kuat.",
  },
  {
    id: "wti",
    name: "WTI Crude Oil",
    short: "WTI",
    category: "pasar",
    country: "GL",
    countryName: "Global",
    freq: "D",
    fred: "DCOILWTICO",
    mode: "level",
    unit: "USD/barel",
    decimals: 2,
    impact: "Low",
    release: "Daily",
    about: "Harga minyak mentah WTI.",
    why: "Harga minyak berdampak pada inflasi & mata uang negara produsen.",
    fx: "Minyak naik → CAD (kadang) & NOK menguat; importir (JPY, EUR) melemah.",
  },
  {
    id: "vix",
    name: "VIX Volatility Index",
    short: "VIX",
    category: "pasar",
    country: "US",
    countryName: "Global",
    freq: "D",
    fred: "VIXCLS",
    mode: "level",
    unit: "index",
    decimals: 2,
    impact: "Low",
    release: "Daily",
    about: "Ukuran volatilitas & ketakutan pasar (CBOE).",
    why: "VIX tinggi → risk-off → safe-haven (USD, JPY, CHF) menguat.",
    fx: "VIX naik → mata uang safe-haven kuat, mata uang risk tinggi melemah.",
  },
  {
    id: "brent",
    name: "Brent Crude Oil",
    short: "Brent",
    category: "pasar",
    country: "GL",
    countryName: "Global",
    freq: "D",
    fred: "DCOILBRENTEU",
    mode: "level",
    unit: "USD/barel",
    decimals: 2,
    impact: "Low",
    release: "Daily",
    about: "Harga minyak mentah Brent (acuan internasional).",
    why: "Bersama WTI, menggerakkan mata uang produsen minyak & memengaruhi inflasi.",
    fx: "Brent naik → CAD/NOK menguat; importir (JPY/INR) tertekan.",
  },
  {
    id: "natgas",
    name: "Natural Gas (Henry Hub)",
    short: "Nat Gas",
    category: "pasar",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "D",
    fred: "DHHNGSP",
    mode: "level",
    unit: "USD/MMBtu",
    decimals: 2,
    impact: "Low",
    release: "Daily",
    about: "Harga gas alam acuan di Henry Hub (AS).",
    why: "Mencerminkan biaya energi AS; berdampak pada inflasi & produsen energinya.",
    fx: "Gas naik → mendukung biaya energi & USD (eksportir energi).",
  },
  {
    id: "copper",
    name: "Copper (Global Price)",
    short: "Copper",
    category: "pasar",
    country: "GL",
    countryName: "Global",
    freq: "M",
    fred: "PCOPPUSDM",
    mode: "level",
    unit: "USD/ton",
    decimals: 0,
    impact: "Low",
    release: "Bulanan",
    about: "Harga tembaga global (USD per metrik ton).",
    why: "Disebut 'Dr. Copper' sebagai penanda kesehatan ekonomi global & permintaan industri.",
    fx: "Tembaga naik → permintaan global kuat → AUD/NZD (produsen) menguat.",
  },
  {
    id: "claims",
    name: "Initial Jobless Claims",
    short: "Jobless Claims",
    category: "tenaga-kerja",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "W",
    fred: "ICSA", // klaim awal mingguan, seasonally adjusted (basis headline & ForexFactory)
    mode: "raw",
    obsRule: "prev-week",
    unit: "orang",
    decimals: 0,
    impact: "Medium",
    release: "Setiap Kamis, 08:30 ET",
    about: "Klaim pengangguran awal per minggu (minggu berakhir Sabtu sebelum rilis).",
    why: "Indikator paling cepat untuk melihat kesehatan pasar tenaga kerja AS.",
    fx: "Klaim naik → ketakutan perlambatan → USD cenderung melemah.",
  },
  {
    id: "capacity",
    name: "Capacity Utilization",
    short: "Capacity",
    category: "pertumbuhan",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "TCU",
    mode: "level",
    unit: "%",
    decimals: 1,
    impact: "Low",
    release: "Sekitar pertengahan bulan",
    about: "Tingkat penggunaan kapasitas industri (%).",
    why: "Kapasitas terpakai tinggi menandakan tekanan inflasi produksi.",
    fx: "Naik → ekonomi memanas → mendukung suku bunga tinggi.",
  },
  {
    id: "eu_gdp",
    name: "Euro Area Real GDP",
    short: "EZ GDP",
    category: "pertumbuhan",
    country: "EZ",
    countryName: "Zona Euro",
    freq: "Q",
    fred: "CLVMNACSCAB1GQEA19",
    mode: "yoy_pct",
    unit: "%",
    decimals: 1,
    impact: "High",
    release: "Perkiraan awal tiap kuartal",
    about: "Pertumbuhan ekonomi riil Zona Euro (year-over-year).",
    why: "Pertumbuhan kuat mendukung kebijakan ECB yang lebih ketat.",
    fx: "GDP EZ kuat → EUR menguat; lemah → EUR melemah.",
  },
  {
    id: "china_cpi",
    name: "China Consumer Price Index",
    short: "China CPI",
    category: "inflasi",
    country: "CN",
    countryName: "Tiongkok",
    freq: "M",
    fred: "CHNCPIALLMINMEI",
    mode: "yoy_pct",
    unit: "%",
    decimals: 1,
    impact: "Medium",
    release: "Sekitar pertengahan bulan",
    about: "Perubahan harga konsumen Tiongkok (YoY).",
    why: "Inflasi China memberi sinyal stimulus kebijakan & permintaan global.",
    fx: "Inflasi tinggi → stimulus bisa dikurangi → CNY cenderung menguat.",
  },
  {
    id: "ismmfg",
    name: "ISM Manufacturing PMI",
    short: "ISM Mfg",
    category: "pertumbuhan",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: null, // ISM tidak tersedia di FRED (lisensi) → data/seed.json + kolom `actual` di data/releases.js
    seedOnly: true,
    mode: "level",
    unit: "index",
    decimals: 1,
    typicalDay: 1,
    impact: "High",
    release: "Tanggal 1–5 tiap bulan (hari irreguler), 10:00 ET (21:00/22:00 WIB)",
    about: "Indeks komposit sektor manufaktur AS dari survei purchasing managers ISM. >50 = ekspansi, <50 = kontraksi.",
    why: "Puls utama 'pertumbuhan manufaktur' — menahankan di atas 50 menjaga narasi ekspansi AS.",
    fx: "PMI Mfg di atas konsensus → ekspektasi Fed hawkish → USD naik; jauh di bawah 50 → USD turun.",
  },
  {
    id: "adp",
    name: "ADP National Employment Report (Private Payrolls)",
    short: "ADP",
    category: "tenaga-kerja",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: "ADPMNUSNERSA", // level tenaga kerja swasta (orang) → selisih bulanan ÷ 1000 = ribu
    mode: "monthly_change_k",
    obsRule: "adp", // rilis 2 hari kerja sebelum NFP (bisa jatuh di akhir bulan yg sama, mis. 30 Sep → data Sep)
    unit: "ribu",
    decimals: 0,
    typicalDay: 3,
    ffDivisor: 1000,
    impact: "High",
    release: "Rabu–Jumat, 2–3 hari kerja sebelum NFP, 08:15 ET (18:15/19:15 WIB)",
    about: "Perubahan jumlah tenaga kerja di sektor swasta (survey ADP) — 'pemanasan' sebelum NFP resmi BLS.",
    why: "Proksi arah umum ketenagakerjaan; kejutan ADP sering (tidak selalu) diikuti NFP pekan yang sama.",
    fx: "ADP kuat → ekspektasi NFP kuat → USD naik; ADP lemah → USD turun.",
  },
  {
    id: "ismsvc",
    name: "ISM Services PMI (Non-Manufacturing)",
    short: "ISM Svc",
    category: "pertumbuhan",
    country: "US",
    countryName: "Amerika Serikat",
    freq: "M",
    fred: null, // ISM tidak tersedia di FRED → seed + kolom `actual` di data/releases.js
    seedOnly: true,
    mode: "level",
    unit: "index",
    decimals: 1,
    typicalDay: 3,
    impact: "High",
    release: "2–3 hari kerja setelah ISM Mfg, 10:00 ET (21:00/22:00 WIB)",
    about: "Indeks komposit sektor jasa AS (±80% PDB) dari survei ISM. >50 = ekspansi; indikator leading paling stabil utk ekonomi AS.",
    why: "Karena sektor jasa mendominasi ekonomi, kejutan Services PMI sering lebih menentukan arah USD daripada manufaktur.",
    fx: "Svc kuat + Prices tinggi → Fed hawkish → USD naik; Svc melambat → ekspektasi cut → USD turun.",
  },
];
// Tolerasi "inline" (±) per indikator — dasar klasifikasi beat/miss & hit-rate.
const TOL = {
  nfp: 25, unemp: 0.15, cpi: 0.15, corecpi: 0.1, ppi: 0.1, corepce: 0.05,
  ahe: 0.1, fedfunds: 0.05, dgs10: 0.05, retail: 0.3, umich: 2, indpro: 0.2,
  gdp: 0.1, eu_cpi: 0.15, eu_unemp: 0.15, uk_cpi: 0.15, uk_unemp: 0.1,
  jp_cpi: 0.2, wti: 2, brent: 2.5, natgas: 0.15, copper: 300, vix: 1.5,
  claims: 10000, capacity: 0.15, eu_gdp: 0.3, china_cpi: 0.15,
  ismmfg: 1.0, ismsvc: 1.0, adp: 10,
};
// Skala tipikal pergerakan per rilis — basis "indeks kejutan" (surpriseIdx):
// surpriseIdx = surprise / scale × 100 → 100 = selebar satu skala tipikal.
const SCALE = {
  nfp: 100, unemp: 0.2, cpi: 0.5, corecpi: 0.4, ppi: 0.4, corepce: 0.15,
  ahe: 0.2, fedfunds: 0.25, dgs10: 0.35, retail: 0.5, umich: 10, indpro: 0.5,
  gdp: 0.5, eu_cpi: 0.5, eu_unemp: 0.2, uk_cpi: 0.5, uk_unemp: 0.2,
  jp_cpi: 0.5, wti: 8, brent: 9, natgas: 0.8, copper: 1000, vix: 5,
  claims: 25000, capacity: 0.5, eu_gdp: 0.8, china_cpi: 0.5,
  ismmfg: 2.0, ismsvc: 2.5, adp: 50,
};

export const SERIES = SERIES_RAW.map((s) => ({ ...s, tol: TOL[s.id] ?? 0.5, scale: SCALE[s.id] ?? 1 }));

export const CATEGORIES = [
  { id: "inflasi", label: "Inflasi", color: "#f0b429" },
  { id: "tenaga-kerja", label: "Tenaga Kerja", color: "#2dd4bf" },
  { id: "moneter", label: "Moneter", color: "#c084fc" },
  { id: "pertumbuhan", label: "Pertumbuhan", color: "#4ade80" },
  { id: "konsumen", label: "Konsumen", color: "#a78bfa" },
  { id: "pasar", label: "Pasar", color: "#94a3b8" },
];

export function getSeries(id) {
  return SERIES.find((s) => s.id === id);
}

export const COUNTRIES = [
  { id: "US", name: "Amerika Serikat", flag: "🇺🇸" },
  { id: "EZ", name: "Zona Euro", flag: "🇪🇺" },
  { id: "UK", name: "Inggris", flag: "🇬🇧" },
  { id: "JP", name: "Jepang", flag: "🇯🇵" },
  { id: "CN", name: "Tiongkok", flag: "🇨🇳" },
  { id: "GL", name: "Global", flag: "🌐" },
];
